# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[1.14,)" # Require at least 1.14.x
# License is REQUIRED after 1.16
license='AFL-3.0'

[[mods]]
modId="omo"
version="${file.jarVersion}"
displayName="OMO"
credits="Someoneice"
authors="Someoneice"
description='''
OMO.
'''
[[dependencies.omo]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.omo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
